server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 80

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mariadb://${rds.hostname}:${rds.port}/${rds.db.name}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${rds.username}
    password: ${rds.password}
  jpa:
    hibernate:
      ddl-auto: none # 배포할때는 디비 직접 만들어야한다.
      default_batch_fetch_size: 100 # in query
    open-in-view: false
logging:
  level:
    '[shop.yeeerim.yeeerimblog]': INFO